### ISSUE TITLE
Multiple hosts in a single dashboard

### ISSUE THREAD

**Issue by rwjack** [ar51an/unbound-dashboard#16]
2.3 is looking great, thank you @ar51an!

I have multiple unbound hosts, so I figure I might document this here in case someone needs it.

Step 1: Add the Unbound Host Variable: (Name, Label, Query Option fields)

![image](https://github.com/user-attachments/assets/2aaced03-5bd2-45e9-bb85-9868f9f03baa)

Step 2: Set the label in the promtail config:

```
 - job_name: unbound
    static_configs:
    - targets:
        - localhost
      labels:
        job: unbound
        host: <DESIRED_HOSTNAME_LABEL> #######################
.... SNIP ....
```

Step 3: Modify the dashboard JSON

Replace all occurences of
`job=\"unbound\"` -> with: `job=\"unbound\", host=\"${unbound_host}\"`

![image](https://github.com/user-attachments/assets/85e1b1d5-b367-4021-a8ad-73baaa315c7b)

Make sure to save the dashboard and voila!

Before:
![image](https://github.com/user-attachments/assets/d58955f9-2a84-4892-b3f9-ef740c6c754e)

After:
![image](https://github.com/user-attachments/assets/9141b522-31e6-44db-8bd8-6ce8d6d01744)
